// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xiUpFWfAUfIUC85b1ejzOFFYnxGIUes',
    appId: '1:439553565816:web:124770eefc393d5c46798d',
    messagingSenderId: '439553565816',
    projectId: 'aututorial-8f62a',
    authDomain: 'aututorial-8f62a.firebaseapp.com',
    storageBucket: 'aututorial-8f62a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7YOy9CtGatNoI6qkyuaAlTd0f4cxJ2U',
    appId: '1:439553565816:android:863ac53640d4b12846798d',
    messagingSenderId: '439553565816',
    projectId: 'aututorial-8f62a',
    storageBucket: 'aututorial-8f62a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXqLZE_mwZMF5R5w0EzoDSn7zTYgJR2A',
    appId: '1:439553565816:ios:0bec7dc9dcac9c8946798d',
    messagingSenderId: '439553565816',
    projectId: 'aututorial-8f62a',
    storageBucket: 'aututorial-8f62a.appspot.com',
    iosClientId: '439553565816-ki0qq4eojb0nefm38jr5ukte4kt6s7ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYXqLZE_mwZMF5R5w0EzoDSn7zTYgJR2A',
    appId: '1:439553565816:ios:bb90656a38729b8646798d',
    messagingSenderId: '439553565816',
    projectId: 'aututorial-8f62a',
    storageBucket: 'aututorial-8f62a.appspot.com',
    iosClientId: '439553565816-lnl968itn8dcb17s0sjtfain0n84vr4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
