// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/local_db.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(3, 2277100393570876092),
      name: 'MyMusic',
      lastPropertyId: const IdUid(6, 330518144611485528),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7809540849503852068),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4623245240522400913),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5997989268819020152),
            name: 'author',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 655151520025627711),
            name: 'url',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3154996457741386593),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 330518144611485528),
            name: 'objectId',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 3058690309199596429),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [
        3676962597740940525,
        9046675569340990162,
        3058690309199596429
      ],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        5295525308706696197,
        214813952248880274,
        6403272070441158292,
        5831445200962725766,
        8179591911006880505,
        4196650191295079836,
        3305239454748278573
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    MyMusic: EntityDefinition<MyMusic>(
        model: _entities[0],
        toOneRelations: (MyMusic object) => [],
        toManyRelations: (MyMusic object) => {},
        getId: (MyMusic object) => object.id,
        setId: (MyMusic object, int id) {
          object.id = id;
        },
        objectToFB: (MyMusic object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final authorOffset = fbb.writeString(object.author);
          final urlOffset = fbb.writeString(object.url);
          final imageOffset = fbb.writeString(object.image);
          final objectIdOffset = fbb.writeString(object.objectId);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, authorOffset);
          fbb.addOffset(3, urlOffset);
          fbb.addOffset(4, imageOffset);
          fbb.addOffset(5, objectIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MyMusic(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              objectId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              author: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              url: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [MyMusic] entity fields to define ObjectBox queries.
class MyMusic_ {
  /// see [MyMusic.id]
  static final id = QueryIntegerProperty<MyMusic>(_entities[0].properties[0]);

  /// see [MyMusic.name]
  static final name = QueryStringProperty<MyMusic>(_entities[0].properties[1]);

  /// see [MyMusic.author]
  static final author =
      QueryStringProperty<MyMusic>(_entities[0].properties[2]);

  /// see [MyMusic.url]
  static final url = QueryStringProperty<MyMusic>(_entities[0].properties[3]);

  /// see [MyMusic.image]
  static final image = QueryStringProperty<MyMusic>(_entities[0].properties[4]);

  /// see [MyMusic.objectId]
  static final objectId =
      QueryStringProperty<MyMusic>(_entities[0].properties[5]);
}
